// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	tidbcluster "github.com/kubernetes-incubator/metrics-server/pkg/apis/tidbcluster"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Instance)(nil), (*tidbcluster.Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Instance_To_tidbcluster_Instance(a.(*Instance), b.(*tidbcluster.Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tidbcluster.Instance)(nil), (*Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tidbcluster_Instance_To_v1alpha1_Instance(a.(*tidbcluster.Instance), b.(*Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceList)(nil), (*tidbcluster.InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstanceList_To_tidbcluster_InstanceList(a.(*InstanceList), b.(*tidbcluster.InstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*tidbcluster.InstanceList)(nil), (*InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_tidbcluster_InstanceList_To_v1alpha1_InstanceList(a.(*tidbcluster.InstanceList), b.(*InstanceList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Instance_To_tidbcluster_Instance(in *Instance, out *tidbcluster.Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ID = in.ID
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_Instance_To_tidbcluster_Instance is an autogenerated conversion function.
func Convert_v1alpha1_Instance_To_tidbcluster_Instance(in *Instance, out *tidbcluster.Instance, s conversion.Scope) error {
	return autoConvert_v1alpha1_Instance_To_tidbcluster_Instance(in, out, s)
}

func autoConvert_tidbcluster_Instance_To_v1alpha1_Instance(in *tidbcluster.Instance, out *Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ID = in.ID
	out.Version = in.Version
	return nil
}

// Convert_tidbcluster_Instance_To_v1alpha1_Instance is an autogenerated conversion function.
func Convert_tidbcluster_Instance_To_v1alpha1_Instance(in *tidbcluster.Instance, out *Instance, s conversion.Scope) error {
	return autoConvert_tidbcluster_Instance_To_v1alpha1_Instance(in, out, s)
}

func autoConvert_v1alpha1_InstanceList_To_tidbcluster_InstanceList(in *InstanceList, out *tidbcluster.InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]tidbcluster.Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_InstanceList_To_tidbcluster_InstanceList is an autogenerated conversion function.
func Convert_v1alpha1_InstanceList_To_tidbcluster_InstanceList(in *InstanceList, out *tidbcluster.InstanceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstanceList_To_tidbcluster_InstanceList(in, out, s)
}

func autoConvert_tidbcluster_InstanceList_To_v1alpha1_InstanceList(in *tidbcluster.InstanceList, out *InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_tidbcluster_InstanceList_To_v1alpha1_InstanceList is an autogenerated conversion function.
func Convert_tidbcluster_InstanceList_To_v1alpha1_InstanceList(in *tidbcluster.InstanceList, out *InstanceList, s conversion.Scope) error {
	return autoConvert_tidbcluster_InstanceList_To_v1alpha1_InstanceList(in, out, s)
}
